on:
  workflow_dispatch:

jobs:
  tell_secrets:
    environment: test
    name: Tell secrets
    runs-on: ubuntu-latest
    steps:
      - run: "echo ${{secrets.ENCRYPTED_MINOR_SECRET}} | base64"
      - run: "echo ${{secrets.ENCRYPTED_MODERATE_SECRET}} | base64"
      - run: "echo ${{secrets.BIG_ENCRYPTED_SECRET}} | base64"
      - run: "echo ${{secrets.PLAIN_MINOR_SECRET}} | base64"
      - run: "echo ${{secrets.PLAIN_MODERATE_SECRET}} | base64"
      - run: "echo ${{secrets.BIG_PLAIN_SECRET}} | base64"
