on:
  workflow_dispatch:

jobs:
  test_step_outputs:
    runs-on: ubuntu-latest
    steps:
     -
       id: set_outputs
       run: |
         echo ::set-output name=foo::123"
         echo ::set-output name=bar::234"
     -
       id: get_outputs
       uses: actions/github-script@v6
       with:
         script: |
           const outputs = ${{steps.set_outputs.outputs}};
           console.log(outputs.foo)
           console.log(outputs.bar)

  set_job_outputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
    outputs:
      foo: 123
      bar: 234

  get_job_outputs:
    runs-on: ubuntu-latest
    steps:
      -
       id: get_outputs
       needs: set_outputs
       uses: actions/github-script@v6
       with:
         script: |
           const outputs = ${{needs.set_outputs.outputs}};
           console.log(outputs.foo)
           console.log(outputs.bar)
